web:
  build: .
  restart: always
  ports: 
    - '3000:3000'
  links: 
    - mongodb
  environment:
    - NODE_ENV=production
    - YOUTUBE_KEY
    - GOOGLE_MUSIC_EMAIL
    - GOOGLE_MUSIC_PASSWORD
  command: npm start
mongodb:
  image: mongo
  volumes:
    - /mongo/data/db:/data/db
