#!/bin/sh

export IMAGE_NAME=${IMAGE_NAME:0:${#IMAGE_NAME} - 6}$GIT_TAG
docker tag -f this $IMAGE_NAME
RETRIES=${RETRIES:-5}
for (( i=0 ; ; i++ )); do
  if [ ${i} -eq ${RETRIES} ]; then
    echo "Too many retries: failed to push the image ${IMAGE_NAME}"
    exit 1
  fi
  docker push $IMAGE_NAME && break
  sleep 1
done
# docker push $IMAGE_NAME 2>&1 | tee /tmp/push-result || true
# while cat /tmp/push-result | grep -q "is already in progress"; do
#    docker push $IMAGE_NAME 2>&1 | tee /tmp/push-result || true
#    sleep 1
# done
run_hook post_push
print_msg "   Pushed image $IMAGE_NAME"
if [ "$EXTERNAL_DOCKER" == "no" ] && [ "$MOUNTED_DOCKER_FOLDER" == "no" ]; then
  print_msg "   Cleaning up images"
  docker rmi -f $(docker images -q --no-trunc -a) > /dev/null 2>&1 || true
fi
